export const EMOTIONS = {
  ANGER: "ANGER",
  HOPE: "HOPE",
  SADNESS: "SADNESS",
  HAPPYNESS: "HAPPYNESS",
  FRUSTRATION: "FRUSTRATION",
  DISAPPOINTMENT: "DISAPPOINTMENT",
  AFFECTION: "AFFECTION",
  DESPERATION: "DESPERATION",
};

export const DAYS_OF_WEEK = {
  SUNDAY: "SUNDAY",
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
};
